language: python
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - DJANGO_SETTINGS_MODULE=pvfree.settings.travis pytest